# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwgJKB8U9d7KtAwhKQANXnGooXCtIMiT

# **EDA**
"""

import matplotlib.pyplot as plt
import requests
import pandas as pd
from bs4 import BeautifulSoup

df = pd.read_csv("/content/pokemon.csv")


df.head()
df.info()
df.describe(include="all")
print("\n missing values:")
df.isnull().sum()

print("dataset shape:", df.shape)

#best 10 pokemon
df["product_name"].value_counts().head(10)

#Price distribution:
#removing the sympol and converting it to a floate

df["product_price"] = df["product_price"].str.replace("£","").astype(float)  # clean price
df["product_price"].hist(bins=20)

print("\nPrice Summary:")
print(df["product_price"].describe())

"""# **histograms for numrics**"""

for col in df.columns:

    if pd.api.types.is_numeric_dtype(df[col]):
        plt.figure(figsize=(6,4))
        df[col].plot(kind="hist", bins=10, title=f"Histogram of {col}")
        plt.xlabel(col)
        plt.show()

if pd.api.types.is_object_dtype(df[col]):
        plt.figure(figsize=(6,6))
        df[col].value_counts().head(5).plot(
            kind="pie",
            autopct="%1.1f%%",
            title=f"Top 5 {col} Distribution"
        )
        plt.show()